# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# # Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run
#       
# version: 2
# jobs:
#   one:
#     docker:
#       - image: circleci/ruby:2.4.1
#     steps:
#       - checkout
#       - run: echo "A first hello"
#       - run: sleep 25
#   two:
#     docker:
#       - image: circleci/ruby:2.4.1
#     steps:
#       - checkout
#       - run: echo "A more familiar hi"
#       - run: sleep 15
# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two
#       
# version: 2
#  workflows:
#    version: 2
#    build-deploy:
#      jobs:
#        - deploy

#  jobs:
#    deploy:
#     docker:
#        - image: circleci/ruby:2.4.1
#      steps:
#        - run: npm install 
#        #     name: Install ant
#        #     command: sudo pip install ant
#        # - run:
#        #     name: Deploy to S3
#        #     command: ant dep
#        
#        
jobs:
  create-open-delete:
    executor: sfdx/default
    # environment:
    #   RES: res
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: 3659080903@qq.com
      - run: echo ./server.key

      # - sfdx/scratch-create:
      #     scratch-alias: circleci
      #     scratch-config: ./config/project-scratch-def.json

      # - run: sfdx force:user:password:generate -u circleci  >> $BASH_ENV
      - run:
         name: 実行時の PATH 書き換えおよび環境変数定義
         command: |
          echo 'export VERY_IMPORTANT=$(sfdx force:org:list)' >> $BASH_ENV
          source $BASH_ENV
      - run: echo $VERY_IMPORTANT
      - run: |
              echo $VERY_IMPORTANT
      # - run: sfdx force:org:list >> /tmp/artifacts.txt
      # - sfdx/scratch-open:
      #     scratch-alias: circleci


      - slack/notify:
          channel: '#general'
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: 'This is a custom message notification $VERY_IMPORTANT'
          webhook: '${SLACK_WEBHOOK}'
      # - sfdx/scratch-delete:
      #     scratch-alias: circleci
      # - run:
      #   name: Upload Failed Tests
      #   command: curl -X POST --data-urlencode "payload={\"channel\": \"#random\", \"username\": \"webhookbot\", \"text\": \"これは webhookbot という名のボットから #random に投稿されています。\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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

      # curl
orbs:
  sfdx: circleci/salesforce-sfdx@2.0.0
  slack: circleci/slack@3.4.2
version: 2.1
workflows:
  basic-test:
    jobs:
      - create-open-delete